@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PayBackParser" as PayBackParser LOGIC_COLOR
participant ":DeleteConfirmationCommandParser" as DeleteConfirmationCommandParser LOGIC_COLOR
participant ":ConfirmationStageParser" as ConfirmationStageParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "c:DeleteConfirmationCommand" as DeleteConfirmationCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("/delete 240001")
activate LogicManager

LogicManager -> PayBackParser : parseCommand("/delete 240001")
activate PayBackParser

create DeleteConfirmationCommandParser
PayBackParser -> DeleteConfirmationCommandParser
activate DeleteConfirmationCommandParser

DeleteConfirmationCommandParser --> PayBackParser
deactivate DeleteConfirmationCommandParser

PayBackParser -> DeleteConfirmationCommandParser : parse("240001")
activate DeleteConfirmationCommandParser

create DeleteConfirmationCommand
DeleteConfirmationCommandParser -> DeleteConfirmationCommand
activate DeleteConfirmationCommand

DeleteConfirmationCommand --> DeleteConfirmationCommandParser :
deactivate DeleteConfirmationCommand

DeleteConfirmationCommandParser --> PayBackParser : c
deactivate DeleteConfirmationCommandParser

DeleteConfirmationCommandParser -[hidden]-> PayBackParser
destroy DeleteConfirmationCommandParser

PayBackParser --> LogicManager : c
deactivate PayBackParser

LogicManager -> DeleteConfirmationCommand : execute(m)
activate DeleteConfirmationCommand

DeleteConfirmationCommand -> Model : setLastMentionedPerson(240001)
activate Model

Model --> DeleteConfirmationCommand : person
deactivate Model

DeleteConfirmationCommand --> LogicManager : "Confirm Delete (Y/N)?"
deactivate DeleteConfirmationCommand

[-> LogicManager : execute("Y")
LogicManager -> ConfirmationStageParser : parseCommand("Y")
activate ConfirmationStageParser

create DeleteCommand
ConfirmationStageParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> ConfirmationStageParser :
deactivate DeleteCommand

ConfirmationStageParser --> LogicManager : d
deactivate ConfirmationStageParser
destroy ConfirmationStageParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

DeleteCommand -> Model : getLastMentionedPerson(240001)
activate Model

Model --> DeleteCommand : person
deactivate Model

DeleteCommand -> Model : deletePerson(person)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : getTransactions(person.id)
activate Model

Model --> DeleteCommand : transactions
deactivate Model

DeleteCommand -> Model : deleteTransactions(transactions)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : setLastMentionedPerson(null)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
