@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PayBackParser" as PayBackParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant ":ConfirmationStageParser" as ConfirmationStageParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "c:DeleteConfirmationCommand" as DeleteConfirmationCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("/delete 240001")
activate LogicManager

LogicManager -> PayBackParser : parseCommand("/delete 240001")
activate PayBackParser

create DeleteCommandParser
PayBackParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> PayBackParser
deactivate DeleteCommandParser

PayBackParser -> DeleteCommandParser : parse("240001")
activate DeleteCommandParser

create DeleteConfirmationCommand
DeleteCommandParser -> DeleteConfirmationCommand
activate DeleteConfirmationCommand

DeleteConfirmationCommand --> DeleteCommandParser :
deactivate DeleteConfirmationCommand

DeleteCommandParser --> PayBackParser : c
deactivate DeleteCommandParser

DeleteCommandParser -[hidden]-> PayBackParser
destroy DeleteCommandParser

PayBackParser --> LogicManager : c
deactivate PayBackParser

LogicManager -> DeleteConfirmationCommand : execute(m)
activate DeleteConfirmationCommand

DeleteConfirmationCommand -> Model : getPerson(240001)
activate Model

Model --> DeleteConfirmationCommand : person
deactivate Model

DeleteConfirmationCommand --> LogicManager : "Confirm Delete (Y/N)?"
deactivate DeleteConfirmationCommand

[-> LogicManager : "Y"
LogicManager -> ConfirmationStageParser : parseCommand(m, "Y")
activate ConfirmationStageParser

create DeleteCommand
ConfirmationStageParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> ConfirmationStageParser :
deactivate DeleteCommand

ConfirmationStageParser --> LogicManager : d
deactivate ConfirmationStageParser
destroy ConfirmationStageParser

LogicManager -> DeleteCommand : execute(m)
activate DeleteCommand

DeleteCommand -> Model : getPerson(240001)
activate Model

Model --> DeleteCommand : person
deactivate Model

DeleteCommand -> Model : deletePerson(person)
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : getTransactions(person.id)
activate Model

Model --> DeleteCommand : transactions
deactivate Model

DeleteCommand -> Model : deleteTransactions(transactions)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : r
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
