@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12

start
repeat
  :User enters the /find command and the
  :name with a keyword to find the employee.;
  :PayBack reads user input;
repeat while () is (Incorrect [Command Format])
->[else];
:PayBack creates a NameContainsKeywordsPredicate object;
:PayBack updates filtered list of employees based on the predicate;
:PayBack displays updated list of employees;
stop
@enduml
