@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedPayBack" as VersionedPayBack MODEL_COLOR
end box

[-> Model : undoPayBack()
activate Model

Model -> VersionedPayBack : undo()
activate VersionedPayBack

VersionedPayBack -> VersionedPayBack :resetData(ReadOnlyPayBack)
VersionedPayBack --> Model :
deactivate VersionedPayBack

[<-- Model
deactivate Model

@enduml
